- id: '1668538185083'
  alias: SelectComputer
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.select_source
    data:
      source: Computer
    target:
      device_id: 061aa623994d3c7cf586bd085e2fce66
  mode: single
- id: '1668867034619'
  alias: Licht Küche Mobil
  description: ''
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 2c5023272665028ae1e5892d1515994e
      button_single_press:
      - device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        domain: light
        entity_id: light.kinderzimmer
        type: brightness_increase
      button_long_press:
      - device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        domain: light
        entity_id: light.kinderzimmer
        type: brightness_decrease
      button_double_press:
      - type: turn_off
        device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        entity_id: light.kinderzimmer
        domain: light
- id: '1669832462775'
  alias: Weihnachtbeleuchtung On
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: e0a513b4dbbee62d0915f6d969facda0
    entity_id: switch.hombli_smart_socket_1
    domain: switch
  mode: single
- id: '1669832519068'
  alias: Weihnachtbeleuchtung Off
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: e0a513b4dbbee62d0915f6d969facda0
    entity_id: switch.hombli_smart_socket_1
    domain: switch
  mode: single
- id: '1669895061075'
  alias: Küche Licht N Long Push
  description: ''
  trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device: Küche
      channel: 2
      click_type: single
    id: testlongpush
    enabled: false
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 62800ac78a288d382f57db3c0545906d
    entity_id: light.spuelbecken
    domain: light
  mode: single
- id: '1669898938917'
  alias: Küche Licht N Single Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: single_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 95b36309b518dfe168d35762ee1a045c
    entity_id: light.kuche_licht
    domain: light
  mode: single
- id: '1670152299285'
  alias: Badezimmer Nat Play
  description: ''
  trigger:
  - device_id: 31cfe845d69d3416c4319e383f33659e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.badezimmer
    data:
      media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/spotify:playlist:0ITaQvQ4I118J36BOHm1pd
      media_content_type: spotify://playlist
    metadata:
      title: Nathalie golden gaul
      thumbnail: https://mosaic.scdn.co/640/ab67616d0000b2735a15602b01795514d058b6edab67616d0000b2739a3da6b52373b762009671cbab67616d0000b273c82a59431ee475300e2f618aab67616d0000b273ca40908d43a2a80fb34de8a3
      media_class: playlist
      children_media_class: track
      navigateIds:
      - {}
      - media_content_type: spotify://library
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396
      - media_content_type: spotify://current_user_playlists
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/current_user_playlists
      - media_content_type: spotify://playlist
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/spotify:playlist:0ITaQvQ4I118J36BOHm1pd
    enabled: false
  - service: media_player.play_media
    target:
      entity_id: media_player.badezimmer
    data:
      media_content_id: FV:2/2
      media_content_type: favorite_item_id
    metadata:
      title: RTS Couleur 3 104.2 (Indie Music)
      thumbnail: http://cdn-radiotime-logos.tunein.com/s15474q.png
      media_class: genre
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: favorites
        media_content_id: ''
      - media_content_type: favorites_folder
        media_content_id: object.item.audioItem.audioBroadcast
  mode: single
- id: '1670159204162'
  alias: Terrasse Girlande Short Push
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: single_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    entity_id: light.terrasse_steckdose
    domain: light
  mode: single
- id: '1670162910894'
  alias: Terrasse Long Push Hallo
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.marantz_heos
    data:
      media_content_id: media-source://tts/google_translate?message=Hallo+Flavia+und+Timea
      media_content_type: provider
    metadata:
      title: Hallo Flavia und Timea
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Hallo+Flavia+und+Timea
  mode: single
- id: '1670318646476'
  alias: Badezimmer Nat Stop
  trigger:
  - device_id: 31cfe845d69d3416c4319e383f33659e
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  condition: []
  action:
  - service: media_player.media_stop
    entity_id: media_player.badezimmer
  mode: single
- id: '1670343600109'
  alias: Badezimmer Nat stop on light off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 9cdc61049d2b05bba87540ebda2a38b6
    entity_id: light.badezimmer
    domain: light
  condition: []
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.badezimmer
  mode: single
- id: '1670442525029'
  alias: Terrasse Long Push Beamer
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - service: rest_command.beamer_on
    data: {}
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.computer_beamer
  mode: single
- id: '1670499646756'
  alias: Küche Licht S Single Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: single_push
    subtype: button2
  condition: []
  action:
  - type: toggle
    device_id: 95b36309b518dfe168d35762ee1a045c
    entity_id: light.kuche_licht
    domain: light
  mode: single
