- id: '1668538185083'
  alias: SelectComputer
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.select_source
    data:
      source: Computer
    target:
      device_id: 061aa623994d3c7cf586bd085e2fce66
  mode: single
- id: '1668867034619'
  alias: Licht Küche Mobil
  description: ''
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 2c5023272665028ae1e5892d1515994e
      button_single_press:
      - device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        domain: light
        entity_id: light.kinderzimmer
        type: brightness_increase
      button_long_press:
      - device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        domain: light
        entity_id: light.kinderzimmer
        type: brightness_decrease
      button_double_press:
      - type: turn_off
        device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
        entity_id: light.kinderzimmer
        domain: light
- id: '1669832462775'
  alias: Weihnachtbeleuchtung On
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: e0a513b4dbbee62d0915f6d969facda0
    entity_id: switch.hombli_smart_socket_1
    domain: switch
  mode: single
- id: '1669832519068'
  alias: Weihnachtbeleuchtung Off
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: e0a513b4dbbee62d0915f6d969facda0
    entity_id: switch.hombli_smart_socket_1
    domain: switch
  mode: single
- id: '1669895061075'
  alias: Küche Licht N Long Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 62800ac78a288d382f57db3c0545906d
    entity_id: light.spuelbecken
    domain: light
  mode: single
- id: '1669898938917'
  alias: Küche Licht N Single Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: single_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 95b36309b518dfe168d35762ee1a045c
    entity_id: light.kueche
    domain: light
  mode: single
- id: '1670152299285'
  alias: Badezimmer Nat Play
  description: ''
  trigger:
  - device_id: 31cfe845d69d3416c4319e383f33659e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  - platform: device
    type: turned_on
    device_id: 9cdc61049d2b05bba87540ebda2a38b6
    entity_id: light.badezimmer
    domain: light
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.badezimmer
    data:
      media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/spotify:playlist:0ITaQvQ4I118J36BOHm1pd
      media_content_type: spotify://playlist
    metadata:
      title: Nathalie golden gaul
      thumbnail: https://mosaic.scdn.co/640/ab67616d0000b2735a15602b01795514d058b6edab67616d0000b2739a3da6b52373b762009671cbab67616d0000b273c82a59431ee475300e2f618aab67616d0000b273ca40908d43a2a80fb34de8a3
      media_class: playlist
      children_media_class: track
      navigateIds:
      - {}
      - media_content_type: spotify://library
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396
      - media_content_type: spotify://current_user_playlists
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/current_user_playlists
      - media_content_type: spotify://playlist
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/spotify:playlist:0ITaQvQ4I118J36BOHm1pd
    enabled: false
  - service: media_player.play_media
    target:
      entity_id: media_player.badezimmer
    data:
      media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/spotify:playlist:6ouM7lgnROKiwCbLYQjQQT
      media_content_type: spotify://playlist
    metadata:
      title: Culture francaise
      thumbnail: https://mosaic.scdn.co/640/ab67616d0000b273159a5ce13b0c1657c87b96bcab67616d0000b2731a33af0f0829ce05885c7bc7ab67616d0000b2735c165929dde4dae330ba33d2ab67616d0000b2735ef15ae660d20a98d43721f1
      media_class: playlist
      children_media_class: track
      navigateIds:
      - {}
      - media_content_type: spotify://library
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396
      - media_content_type: spotify://current_user_playlists
        media_content_id: spotify://4c8b5c29d2e8eadf36ea31787c816396/current_user_playlists
    enabled: false
  - service: media_player.play_media
    target:
      entity_id: media_player.badezimmer
    data:
      media_content_id: FV:2/2
      media_content_type: favorite_item_id
    metadata:
      title: RTS Couleur 3 104.2 (Indie Music)
      thumbnail: http://cdn-radiotime-logos.tunein.com/s15474q.png
      media_class: genre
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: favorites
        media_content_id: ''
      - media_content_type: favorites_folder
        media_content_id: object.item.audioItem.audioBroadcast
  mode: single
- id: '1670159204162'
  alias: Terrasse Girlande Short Push
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: single_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    entity_id: light.terrasse_steckdose
    domain: light
  mode: single
- id: '1670162910894'
  alias: Terrasse Long Push Hallo
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 80c99e91ca7ffea365533d0c36ccfafe
    entity_id: switch.hombly_socket_2
    domain: switch
  mode: single
- id: '1670318646476'
  alias: Badezimmer Nat Stop
  trigger:
  - device_id: 31cfe845d69d3416c4319e383f33659e
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  - platform: device
    type: turned_off
    device_id: 9cdc61049d2b05bba87540ebda2a38b6
    entity_id: light.badezimmer
    domain: light
  condition: []
  action:
  - service: media_player.media_stop
    entity_id: media_player.badezimmer
  mode: single
- id: '1670343600109'
  alias: Badezimmer Nat stop on light off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 9cdc61049d2b05bba87540ebda2a38b6
    entity_id: light.badezimmer
    domain: light
  condition: []
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.badezimmer
  mode: single
- id: '1670442525029'
  alias: Terrasse Long Push Beamer
  description: ''
  trigger:
  - platform: device
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    domain: shelly
    type: long_push
    subtype: button1
  condition: []
  action:
  - service: rest_command.beamer_on
    data: {}
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.computer_beamer
  mode: single
- id: '1670499646756'
  alias: Küche Licht S Single Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: single_push
    subtype: button2
  condition: []
  action:
  - type: toggle
    device_id: 95b36309b518dfe168d35762ee1a045c
    entity_id: light.kueche
    domain: light
  mode: single
- id: '1670508071488'
  alias: Küche Licht S Long Push
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: long_push
    subtype: button2
  condition: []
  action:
  - type: toggle
    device_id: bdd792544ccee16e7e5081589ad95f9a
    entity_id: switch.hombly_socket_3
    domain: switch
  mode: single
- id: '1675108135406'
  alias: Girlande Fenster
  description: ''
  trigger:
  - platform: device
    device_id: 0cb3db7867669f14d5560252bad5abc4
    domain: shelly
    type: single
    subtype: button2
  condition: []
  action:
  - type: toggle
    device_id: a7ccfc6164c35010220130aa3783a3dc
    entity_id: switch.fenster_steckdose
    domain: switch
  mode: single
- id: '1675111619707'
  alias: debug shelly
  description: ''
  trigger:
  - platform: device
    device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
    domain: shelly
    type: single
    subtype: button1
  condition: []
  action:
  - type: toggle
    device_id: 8b9c9effd2696b0c9a31eb31b6a5679b
    entity_id: light.kinderzimmer
    domain: light
  mode: single
- id: '1675332855531'
  alias: Küchentisch Gedimmt
  description: ''
  trigger:
  - platform: device
    device_id: 0cb3db7867669f14d5560252bad5abc4
    domain: shelly
    type: long
    subtype: button1
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 29
    target:
      device_id: 0cb3db7867669f14d5560252bad5abc4
  mode: single
- id: '1675334841799'
  alias: Küchentisch off->on
  description: ''
  trigger:
  - platform: device
    device_id: 0cb3db7867669f14d5560252bad5abc4
    domain: shelly
    type: single
    subtype: button1
  condition:
  - condition: device
    type: is_off
    device_id: 0cb3db7867669f14d5560252bad5abc4
    entity_id: light.kuechentisch
    domain: light
  action:
  - type: turn_on
    device_id: 0cb3db7867669f14d5560252bad5abc4
    entity_id: light.kuechentisch
    domain: light
    brightness_pct: 100
  mode: single
- id: '1675335071609'
  alias: Küchentisch on->off
  description: ''
  trigger:
  - platform: device
    device_id: 0cb3db7867669f14d5560252bad5abc4
    domain: shelly
    type: single
    subtype: button1
  condition:
  - condition: device
    type: is_on
    device_id: 0cb3db7867669f14d5560252bad5abc4
    entity_id: light.kuechentisch
    domain: light
  action:
  - type: turn_off
    device_id: 0cb3db7867669f14d5560252bad5abc4
    entity_id: light.kuechentisch
    domain: light
  mode: single
- id: '1675369154855'
  alias: Küche S Girlande
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: long_push
    subtype: button2
  condition: []
  action:
  - type: toggle
    device_id: 6b4fa1ddb6ab610e2fc7c621fc02061a
    entity_id: switch.terrasse_girlande
    domain: switch
  mode: single
- id: '1675379653120'
  alias: test slow turn on
  description: ''
  trigger:
  - platform: device
    device_id: 95b36309b518dfe168d35762ee1a045c
    domain: shelly
    type: double_push
    subtype: button2
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 25
      brightness_pct: 25
    target:
      device_id: 0cb3db7867669f14d5560252bad5abc4
  mode: single
- id: '1675450639597'
  alias: Mädels Music Play
  description: ''
  trigger:
  - platform: device
    device_id: 0cb3db7867669f14d5560252bad5abc4
    domain: shelly
    type: long
    subtype: button2
  condition: []
  action:
  - service: media_player.select_source
    data:
      source: Marantz NR1510
    target:
      entity_id: media_player.spotify_spotifykusi
    enabled: true
  - service: media_player.play_media
    target:
      entity_id: media_player.spotify_spotifykusi
    data:
      media_content_id: spotify:track:7MOdFbxbHrbS4BK4k8O2dj
      media_content_type: spotify://track
    metadata:
      title: Mettmenstetten
      thumbnail: https://i.scdn.co/image/ab67616d0000b2737e2e218329c9d2f79717c36f
      media_class: track
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: spotify://current_user_recently_played
        media_content_id: current_user_recently_played
    enabled: true
  - service: media_player.play_media
    target:
      entity_id: media_player.family_room_tv
    data:
      media_content_id: media-source://media_source/local/sayhi.mp3
      media_content_type: audio/mpeg
    metadata:
      title: sayhi.mp3
      thumbnail:
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://media_source
    enabled: false
  - if:
    - condition: device
      device_id: 8372f3f81f225cb560d9081a91ff1b24
      domain: media_player
      entity_id: media_player.spotify_spotifykusi
      type: is_playing
      enabled: false
    - condition: template
      value_template: '{{ true }}'
    then:
    - service: media_player.media_pause
      data: {}
      target:
        entity_id: media_player.marantz_heos
    else:
    - service: media_player.play_media
      target:
        entity_id: media_player.spotify_spotifykusi
      data:
        media_content_id: spotify:track:7MOdFbxbHrbS4BK4k8O2dj
        media_content_type: spotify://track
      metadata:
        title: Mettmenstetten
        thumbnail: https://i.scdn.co/image/ab67616d0000b2737e2e218329c9d2f79717c36f
        media_class: track
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: spotify://current_user_recently_played
          media_content_id: current_user_recently_played
    - service: light.toggle
      data: {}
      target:
        entity_id: light.badezimmer
    enabled: false
  mode: single
- id: '1675554209925'
  alias: debug condition
  description: ''
  trigger: []
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{{ false }}'
    then:
    - event: kusi
      event_data:
        kusi: then
    else:
    - event: kusi
      event_data:
        kusi: else
  mode: single
